<h3>1. Mindig menj be órára</h3>
<p>Kézenfekvőnek tűnhet, de előbb utóbb rájössz, hogy mindig lesz valami egyszerű kifogásod (regisztrációs hét van, ez még csak a második hét, 3* lehet hiányozni, stb…). Az anyag általában minden kurzuson könnyen indul, de 1-2 kihagyott óra után roppant könnyű elveszteni a fonalat.</p>
<h3>2. Csatlakozz valamilyen csapathoz, vagy közösséghez</h3>
<p>Ha lehetőséged van csatlakozni valamilyen csapathoz / közösséghez, tedd meg! Semelyik szak nem készít fel úgy az életre, mintha tagja lehetsz egy csapatnak, legyen szó sportról, kollégiumi szeniorokról, HÖK képviselőkről, vagy a helyi anime és társasjáték klubról.</p>
<p>Én például amerikai fociztam, koli rádióztam, voltam szenior, rendszergazda, és még egy anime/társasjáték klubbot is csináltam (PandAnime). Volt ami bejött, volt ami nem, egy biztos: rengeteg jó embert ismertem meg, és sokat tanultam (magamról is). Ha olyan vagy akit a <strong>honvágy gyakran gyötör</strong>, az elején mindenképpen szánd rá magad 1-2 ilyenre. Ha sikerül szerezned&nbsp;pár barátot, hamar rájössz, hogy igazából ez is ugyanúgy az otthonod.</p>
<h3>3.&nbsp;MINDIG készíts biztonsági mentést a fájljaidról.</h3>
<p>Ez egészen addig nem lesz fontos, míg vizsga előtt elő kéne venned a digitális jegyzeteidet, de el sem indul a géped. Én Google Drive-ot és Dropboxot használtam fájlok tárolására, és <x-a href="https://www.evernote.com/" target="_blank" rel="noopener">Evernote</x-a>-ot órán való jegyzetelésre.</p>
<h3>4. Használj vírusírtót</h3>
<p>Infósként én alapból odafigyeltem a vírusok elleni védelemre, de több szaktársam gépét vitte el valami keménykötésű kártevő. Mondanom sem kell, hogy főleg a srácok hullottak ki a pornó miatt, és szörnyülködve látták, hogy egy ingyenes Nod32 milyen sok kártevőt képes levadászni böngészés közben. Arról nem is beszélve, hogy manapság rettentően népszerűek azok a vírusok, melyek titkosítják a merevlemezt, és csak pénzért hajlandóak visszaadni az adataidat. Vagy még akkor sem.</p>
<h3>5. Kezdj el ismerkedni a pénzügyekkel.</h3>
<p>Nem kell annyira beleásnod magad, mint a számvitel szakosoknak, de ha belebotlasz egy pénzes cikkbe, olvasd el. Ha valamit nem értesz, keress rá. Hidd el, idővel egyre világosabb lesz minden, és minél előbb kezded el megérteni a pénzügyi világot, annál nagyobb esélyed van sikeresnek lenni. Próbáld meg beosztani a pénzed az általunk készített <x-a href="{{ route('beosztom.diak') }}">Beosztom.hu</x-a> alkalmazással, vagy olvasgass hasznos cikkeket a <x-a href="http://kiszamolo.hu" target="_blank" rel="noopener">kiszamolo.hu</x-a> vagy a <x-a href="http://haszon.hu" target="_blank" rel="noopener">haszon.hu</x-a> oldalakon.</p>
<h3>6. Keress állást!</h3>
<p>Persze csak finoman, de ha szüleid tartanak el, képzeld magadat a helyükbe. Tényleg a kemény munkával megkeresett pénzüket akarod elverni bulikra és kávézókban? Mindazonáltal a munka talpraesetté és tapasztalttá tesz, ráadásul lesz mit beírni az önéletrajzodba.</p>
<p>A minap érkezett be hozzánk egy 26 éves srác önéletrajz a meghirdetett állásra, 0 nap munkatapasztalattal. Alapvetően nincs ezzel semmi baj, szinte minden munkahelyen betanítják az embert, viszont aki már több területen is dolgozott, általában sokkal rugalmasabb, fogékonyabb az új dolgokra, és jobban kijön a kollégákkal.</p>
<h3>7. Alapíts vállalkozást!</h3>
<p>Ehhez azért már tudni kell valamit, én például weboldalakat készítettem. 18 éves koromban olyan egyéni vállalkozást hoztam létre, ahol csak akkor kellett fizetni az államnak egy bizonyos %-ot (talán 40% volt), ha volt bevételem. Évi 100-200.000 ft bevételnél ez még bőven jó, azonban ha tényleg jó vagy valamiben, például angol nyelvórákat tartasz, vagy kisebb csoportokat korrepetálsz analízisből 1000 Ft / Fő / óra áron, akkor azért elég hamar összejön akár a félmillió forint is. Ma már úgynevezett KATA vállalkozásom van, ahol havi 25.000 ft-ot fizetek <em>(ha hallgató vagyok, vagy van egy másik főállásom, egyébként 50.000)</em> az állam felé (évi 300.000 Ft), viszont efölött minden pénz az enyém (egészen 8 millióig, onnantól már bonyolultabb).</p>
<h3>8. Válassz megfelelő bankszámla csomagot!</h3>
<p>Általában minden banknál van egy egyetemistáknak szóló kedvezményes csomag pl. <x-a href="https://www.otpbank.hu/portal/hu/junior" target="_blank" rel="noopener">OTP junior</x-a> vagy a <x-a href="https://www.magnetbank.hu/koltson-bankra-kevesebbet-csillag" target="_blank" rel="noopener">MagnetBank Csillag számla csomagja</x-a>. Arra figyelj, hogy az utalásokért szinte mindig kell plusz díjat fizetni, míg a bankkártyás vásárlásokért nem. Ahol lehet, ott válaszd az online bankkártyás fizetést <em>(a <x-a href="{{ route('jobb-jegyek') }}">Jobb jegyek 10 lépésben</x-a> könyvünket is ki tudod így fizetni, ha a Barion opciót választod)</em>.</p>
<h3>9. Hozz magaddal elég ruhát a koliba!</h3>
<p>Törvény biztosítja, hogy minden koliban álljon rendelkezésre mosógép, azonban azt senki nem garantálja, hogy ezek folyamatosan működni is fognak. A mi kolinkban például volt 8 mosógép, ebből 3 folyton szerelés alatt, a maradék 5 pedig 400 diák koszos ruháira éhezett. Mondanom sem kell, hogy amikor hajnali 4-kor reménnyel telve lesomfordáltam a mosókonyhába, 6-an ültek előttem zombi módban, várva, hogy lejárjon más éjjeli baglyok mosása. Tehát legyen ruhád a következő hazamenetelig, különben könnyen lehet hogy 3 napos, izzadt göncökben fogsz ülni a következő telt termes kurzusodon.</p>
<h3>10. Mindig tudd, mikor ér véget a mosás!</h3>
<p>Mivel valószínűleg rengetegen várnak mosásra, senki nem fog kesztyűs kézzel bánni a ruháddal, ha lejárt a mosásod, de te nem vagy ott, hogy kivedd a gépből. Vannak ugyan jó arcok, akik lavórba teszik, de ha nem akarod, hogy a csipkés bugyidat kanos fiúk, vagy irigy lányok nyúlják le, vagy csak szimplán a sarokban landoljon, akkor állíts be magadnak emlékeztetőt a telefonon.</p>
<h3>11. Az alvás nagyon fontos.</h3>
<p>Sokan kávéval és energiaitallal próbálják magukat minden nap életre kelteni, de ez semmi másra nem jó, csak hogy átvészeld a napot. Képtelen leszel összpontosítani órán, pedig a legtöbbet akkor lehet tanulni. Ha fitten oda tudsz figyelni és megérted, hogy miről beszél a tanár, a tanulás felén már túl is vagy.</p>
<h3>12. Ha problémád van a szobatársaddal, beszélj vele</h3>
<p>Néhány kollégiumban van lehetőség szobacserére, sokban azonban nincs <em>(ahol van, ott is előbb találnod kell valakit, aki majd hajlandó lesz a te helyedre költözni).</em> Éppen ezért egy szobatárs általában legalább egy évre szól, márpedig nekem nem lenne kedvem kerülgetni valakit 1 éven keresztül a saját szobámban.</p>
<p>Laktam már együtt nagyon kövér sráccal, olyannal aki dohányzott, olyannal aki hajnali 6-kor jött vissza minden nap a szobába, volt aki úgy falta a barátnőjét a szomszéd ágyon, hogy cseppet sem érdekelte, hogy én ott vagyok. Mindegyikkel voltak nézeteltéréseim, de mindig meg tudtam beszélnivelük. Vannak akik inkább hallgatnak, és olyanok is, akik megpróbálják a másik életét pokollá tenni. Te egyik se legyél! Ülj le, beszéld meg, köss kompromisszumot!</p>
<h3>13. Keress diákmunkát!</h3>
<p>MindDiák, Meló-diák, Fürge-diák… végtelenségig lehetne sorolni a diákszövetkezeteket, akiken keresztül munkát lehet kapni. Azt tanácsolom, hogy valami munkát mindenképpen nézz, viszont ez ne menjen se a tanulás, se a kikapcsolódás rovására. Ismerősöm suli után kapásból ment vendéglátóhelyre pultozni, onnan pedig buliba. Csúszott 3 évet, a keresett pénze pedig diákhitel törlesztésre ment el.</p>
<p>A hirdetésekben arra is figyelj oda, hogy pontosan mennyit kínálnak! A bruttó 1.000 Ft-ból kb. 850 Ft marad meg neked az adók levonása után, ami persze nem kevés, csak ne lepődj meg, hogy 40 óra munka után 40.000 Ft helyett csak 34.000 Ft-ot kapsz.</p>
<h3>14. Kössd össze a hasznosat egy másik hasznossal</h3>
<p>Ha nem találsz részmunkaidős állást, bevállalhatsz teljes munkaidőset is, azonban ilyenkor érdemes olyant keresni, ahol munka közben van lehetőség tanulásra is. Gyártósor és vendéglátás helyett keress inkább könyvtáros munkát, vagy próbáld ki magad recepciósként.</p>
<h3>15. Menj Erasmus-szal külföldre</h3>
<p>Ha az egyetemeden van lehetőség Erasmusra, vagy a külföldi diákokkal való kapcsolattartásre, élj vele! Én nem mentem ki külföldre, mert nem voltam elég magabiztos, helyette a vendéglátó helyemen Afrikából jött cserediákokkal beszélgettem. Sosem fejlődtem még annyit angolból, mint az alatt a pár hét alatt! Barátom kétszer volt kint Erasmus programmal külföldön ingyen, utána pedig akikkel összebarátkozott, minden évben elhívták 1 hétre nyaralni. Ingyen.</p>
<h3>16. Ismerd meg a tanárod!</h3>
<p>A (jó) tanárok olyan emberek, akiknek örömet okoz, ha diákjaik érdeklődnek az általuk tanított témák iránt. Ha van olyan tárgy ami őszintén érdekel, bátran keresd fel az oktatót fogadóóráján, hidd el, rá fog érni. Nekem olyan szerencsém volt, hogy a tanáromtól kisebb munkákat is kaptam, később pedig az alapján készítettem el a szakdolgozatomat.</p>
<h3>17. A tojás felrobban a mikróban.</h3>
<p>Kipróbáltuk. 12.000-ért vehettünk egy újat, mert a forgótányér ripityára tört, és külön nem árultak hozzá. <x-a href="https://www.youtube.com/watch?v=0vX25CqgrZ4" target="_blank" rel="noopener">Szintcsúszást is rendeztünk</x-a>, tök mókás volt 5 liter mosogatószerrel fellocsolni a folyosót, utána viszont 4 órán át tart felmosni, mert csak habzik, habzik, és habzik. <x-a href="https://www.youtube.com/watch?v=WFQU6UoA2sg" target="_blank" rel="noopener">Következő alkalommal</x-a> úgy kezdtük, hogy takarófóliával terítettük be a szintet. Tanulj a hibáinkból!</p>
<h3>18. Ne gyere kocsival</h3>
<p>Egyrészt fizetheted a parkolót, ha normális helyen akarod tudni a kocsidat, másrészt kétséged se legyen afelől, hogy mindenki a legjobb barátod lesz majd arra a fél órára, amíg elviszed őket a boltba. “Fizetek a benzinbe” – said no student ever.</p>
<h3>19. Ha mégis kocsival jössz…</h3>
<p>Akkor viszont fizess a kolinál parkolásért, és parkolj a kamera közelébe, mert ha valahol, akkor itt tuti letörik egy buli alkalmával a visszapillantó tükrödet. Ami pedig az ingyen fuvarokat illeti, nos, legyél talpraesett, és barterezz! Én lelkiismeretfurdalás nélkül hivattam meg magam vacsorára azokban a szobákban ahova alapanyagot vettünk.</p>
<p>Arra azért figyelj, hogy pénzt ne kérj semmiért, mi egy ideig a buszpályaudvarról szállítottunk diákokat a koliba, aztán felhívták rá a figyelmünket, hogy ez bizony taxi szolgáltatás, és törvényt sértünk.</p>
<h3>20. Kollégium vagy albérlet?</h3>
<p>Ha választási lehetőséged van kollégium és albérlet között, gondolkodás nélkül a kollégium mellett dönts! Bár az egyetem a tanulásról szól, életed legfontosabb kapcsolatait alapozhatod meg egy jó kollégiumban. Ne érts félre, voltak nagyon jó albis haverjaink, de az esetek 90%-ban ők jöttek a koliba át, és nem mi mentünk hozzájuk.</p>
<p>Egy kollégiumban (főleg ahogy egyre több emberrel ismerkedsz meg) hatalmas tered van. Nem mondom, hogy a 2 szobás albérletben nyomorognánk, de 40 négyzetméteren nem szokott annyi dolog történni, mint mondjuk egy 5 szintes 500 ágyas koliban.</p>
<h3>21. Ha elmúltál 18, felnőtt vagy.</h3>
<p>Azért fontos ezt tudatosítanod magadban, mert egyre többször kerülsz majd olyan helyzetbe, ahol szüleid nélkül, magadra utalva kell ügyeket intézned, és döntéseket hoznod.</p>
<p>Azt se felejtsd el, hogy felelősséggel tartozol a tetteidért, és egyre kisebb az esélye, hogy majd legyinteni fognak: “Ő még csak gyerek”. Láttunk már durva dolgokat részeg egyetemistáktól, és a legtöbbször nincs is belőle baj, de minden évben ébred valaki <em>másnap</em> kórházban. Persze nem kell rástresszelni, ahogy az egyetemünk jogásza szokta mondani: Amíg nincs baj, addig nincs baj.</p>
<h3>22. Tanulj hatékonyan</h3>
<p>Ha még nem tetted, találd ki, hogyan tudsz a leghatékonyabban tanulni. Van aki magányos farkasként, van aki csoportban, van aki a szobájában, van aki kilátó tetején, az egyik zenét hallgatva, a másik síri csendben. <x-a href="{{ route('articles.public_show', 'hatekony-tanulas-muveszete-tanulasi-technikak') }}">Itt összeírtam néhány módszert</x-a> amit én használtam, és szerintem neked is hasznos lehet.</p>
<h3>23. A korrepetálás nem szégyen</h3>
<p>Én lineáris algebra és analízis korrepetálásra jártam, mert valamikor a 6. óra után teljesen elvesztettem a fonalat. Szerencsém volt, mert egy egyetemista srác tartotta, ráadásul ingyen. Azért jó egyetemisták közül tanárt választani, mert benne valószínűleg még frissen él a megértés élménye. A tanárok nagyon bölcsek, viszont amit legtöbbször elfelejtenek, azok nüansznyi dolgok amin a megértés múlhat. Aki emlékszik arra, hogyan értette meg az anyagot, veled is könnyebben meg tudja majd értetni.</p>
<h3>24. Legyen fürdő papucsod!</h3>
<p>Sokaknak ez természetes egy koliban, de hidd el, rengetegen mennek nélküle fürdeni a közös fürdőbe. Lehet, hogy a te kolidban mindenki ultra igényes, ettől függetlenül bárki elkaphat valahol egy lábgombát, amit aztán a közös fürdőben szépen tovább is fog adni. Nincs annál rosszabb, mint amikor reggel 8-ra bemész órára, este 6-kor ér véget az utolsó laborod, és addig a gombás izzadt lábad bent rohad a cipődben. Előzd meg, használj papucsot a zuhanyzóban!</p>
<h3>25. Jegyzetelj!</h3>
<p>Mindegy, hogy füzetbe, vagy laptopon Evernote-ba jegyzetelsz, a lényeg, hogy csináld. Lehet, hogy a haverod is jegyzetel, viszont simán lehet, hogy teljesen másképp jár az agya, mint neked. Az én jegyzeteimet például sokan nem értették, mert nem folyóírásban rögzítettem amit a tanár mondott, hanem kevertem a lista, Cornell és folyamat ábra módszert. <x-a href="https://hu.pinterest.com/pandaegyetem/jegyzetel%C3%A9s/" target="_blank" rel="noopener">Füzetbe gyönyörű jegyzeteket tudsz készíteni</x-a>, a digitális jegyzeteket pedig akár el is adhatod másoknak.</p>
<p>A <x-a href="{{ route('jobb-jegyek') }}">könyvemben</x-a> egy teljes fejezet a jegyzetelésről szól.</p>
<h3>26. Mindig legyél tisztában a tanév rendjével!</h3>
<p>Tantárgy felvétel, vizsgaidőszak kezdete, kollégiumi kiköltözés határideje… mind-mind olyan időszak, amiből ha kicsúszol, akkor sok bosszúság veszi majd kezdetét. </p>
<h3>27. Reggel ébredj fel</h3>
<p>Balgaságnak hangzik, de néhány átbulizott éjszaka után hidd el, esélyed sem lesz kikelni az ágyból. Ha ébresztőt állítasz a telódon, ne az ágy mellé tedd! Szobatársam 6-szor visszanyomta a szundit, és sokkal ramatyabbul nézett ki, mint amikor néha napján rászánta magát arra, hogy egyből kipattanjon az ágyból. Ha egy hangyányit elkezded használni az agyad vagy a tested ébredés után, sokkal könnyebben megy a kelés.</p>
<p>Nekem például van egy rutinom: ahogy kinyitom a szemem, kapásból indulok fogat és arcot mosni. Mire lejár a 2 perces elektromos fogkefe program, már teljesen magamnál vagyok. Azért tudom ezt megtenni, mert amikor még csak a fogkrémet nyomom, gyakorlatilag robot üzemmódban vagyok, csak fogmosás felénél ébredek fel igazán. <x-a href="{{ route('articles.public_show', '7-ebredest-segito-alkalmazas') }}" target="_blank" rel="noopener">Összeszedtem neked 7 telefonos appot, ami segít az ébredésben.</x-a></p>
<h3>28. Kezdj el használni egy naptárat (ha még nem tennéd)!</h3>
<p>Én például Google calendart használok. Fel voltam iratkozva az egyetemi naptárakra, amik mellé rögzítettem a ZH és vizsga időpontokat, továbbá az órarendet is belevarázsoltam ismétlődő eseményekként. Szó se róla, eszméletlen zsúfolt volt, de legalább mindig tudtam, hogy éppen hol kell(ene) lennem.</p>
<h3>29. Fedezd fel az egyetemet!</h3>
<p>A Debreceni Egyetem oldalán <x-a href="https://unideb.hu/hu/elerhetosegek" target="_blank" rel="noopener">van egy tök jó térkép</x-a>, ahol megnézheted az összes egyetemhez kapcsolódó épületet és szolgáltatást. Sajnos nem mindenhol van ez így. Mikor egyszer a W épületben volt egy “Világegyetem megismerése” ingyen kredites órám, lekéstem a feléről, mert nem találkoztam olyan emberrel, aki tudta volna, hol van. Szégyen, de nem is tudtam, hogy az egyetemnek a veszprémi vár területén is van épülete, mi több, egy egész kar tanyázik ott.</p>
<h3>30. Járj utána, hogy milyen szolgáltatásokat biztosít az egyetem!</h3>
<p>Van-e egyetemi orvos, ingyen kondi, menzai étkeztetés, használhatod-e esetleg a Cisco labort, vagy bemehetsz-e a csillagvizsgálóba tanításon kívül. Jár-e bármilyen kedvezmny a városban azért, hogy te egyetemista vagy? Egyetemi gyógyszertár, kedvezmény a tömegközlekedésben, olcsóbb belépő állatkertbe vagy múzeumba, ingyenes bérlet a városi uszodába…</p>
<p>Sok város, és a városon belül működő vállalkozás megpróbál kedvezni nektek. Előbbi azt szeretné, ha a jövőben is sok-sok egyetemista érkezne a városba, esetleg később le is telepednek itt, utóbbi pedig potenciális marketing forrásnak tekint rátok.</p>
<p>Egy elégedett vásárló az 500 fős koliban nagy valószínűséggel további vásárlókat fog eredményezni a vállalkozásnak ugyanabból a koliból. Használd ki! Mondd a fodrásznak, hogy hozol 20 embert hozzá a koliból, ha innentől ingyen vágja a hajad. Ha fodrász lennék, én elfogadnám az ajánlatot.</p>
<h3>31. Írj naplót!</h3>
<p>7-8 év múlva, mikor már dolgozni fogsz, nagyon jó lesz visszaolvasni, hogy honnan indultál, és hogyan gondolkodtál régen. Mintha egy teljesen más ember írta volna a sorokat… de ez nem baj. Innen tudod, hogy fejlődsz.</p>
<h3>32. Ha van állásbörze az egyetemeden, menj el rá!</h3>
<p>Egyrészt tök jó tanácsokat szoktak adni önéletrajz írással kapcsolatban, másrészt megtudhatod, hogy milyen elvárások vannak az egyes munkahelyeken, és miket kaphatsz cserébe. Persze az sem utolsó szempont, hogy kismillió cuccal fognak elhalmozni, ha megadod nekik mondjuk az e-mail címed.</p>
<h3>+1. Lépj ki a komfort zónádból!</h3>
<p>Egyetem előtt egy visszahúzódó, magamnak való srác voltam, nagyon nehezemre esett új kapcsolatokat kialakítani. Rájöttem, hogy így nem fogom sokra vinni, ezért ha volt időm, amin csak lehetett részt vettem. Életem egyik legjobb döntése volt, bár nem tagadom nagyon sok erőfeszítést igényelt az elején.</p>
<h2>Végszó</h2>
<p>Egyetemre tanulni jön az ember, bár az én tapasztalatom az, hogy korán sem tudják leadni azt a tudást, amire neked majd a munkahelyen szükséged lesz. Éppen ezért használd ki az egyetem és kollégium által nyújtott lehetőségeket, építs kapcsolatokat, érezd jól magad.</p>
<p>Ha mégis eljön a tanulás ideje, akkor olvasd el a Jobb jegyek 10 lépésben könyvemet, illetve a cikkeket amiket megosztottam az oldalon. Minden ami le van írva saját tapasztalat, első kézből, tőlem, neked.</p>
<x-a href="{{ route('jobb-jegyek') }}"><img loading="lazy" class="alignnone size-medium wp-image-162" src="{{ asset('images/cikkek/jobb-jegyek-10-lepesben-fb-preview-image-768x403.jpg') }}" alt="" width="768" height="403"></x-a></p>
