<h2><x-a href="https://play.google.com/store/apps/details?id=com.ingyomate.shakeit&amp;hl=hu" target="_blank" rel="noopener">1. Shake-it Alarm</x-a></h2>
<p>Ha gyakran nyomkodod a szundi gombot, ez az ébresztő tökéletes lesz számodra, mert beindítja a vérkeringésed! A kikapcsoláshoz 8-10 másodperc masszív rázásra van szükség, miközben mókás animációk kíséretében feltöltődik egy a sáv. Ha meguntad a rázást, van tapicskolós mód is benne, sőt olyan is ahol ordibálással kell kikapcsolni az ébresztőt. Nem mondom, hogy egy kollégium-barát alkalmazás, de nekem mindenképpen ez a kedvencem!</p>
<p><img loading="lazy" class="alignnone size-medium wp-image-710" src="{{ asset('images/cikkek/evil-alarm-shake-it-android.jpg') }}" alt="ébresztő app android" width="670" height="492"></p>
<h2><x-a href="https://play.google.com/store/apps/details?id=com.wroclawstudio.puzzlealarmclock&amp;hl=en" target="_blank" rel="noopener">2. Puzzle Alarm Clock</x-a></h2>
<p>Akibe reggelente nem lehet egy kis mozgással életet önteni, arra talán nagyobb hatással van egy kis agytorna. Ha 30 másodpercig dolgozik az agy, kitisztulnak belőle az álommanók, és onnantól már nincs szükség különösebb erőfeszítésre a teljes ébredéshez. Ez az alkalmazás minden reggel néhány mini puzzle feladattal tesz próbára. Van matek feladat, memória játék, vagy minta keresős (kép lent). Egymás után max 5 feladatot lehet megoldani, de amikor én próbáltam, nekem 3 bőven elég volt a kijózanodáshoz.</p>
<p><img loading="lazy" class="alignnone size-medium wp-image-711" src="{{ asset('images/cikkek/puzzle-alarm-clock.png') }}" alt="Android ébresztő app" width="640" height="363"></p>
<h2><x-a href="https://itunes.apple.com/us/app/barcode-alarm-clock/id731358084?mt=8" target="_blank" rel="noopener">3. Barcode Alarm Clock Pro (IOS)</x-a></h2>
<p>Ha sem a telefon rázás, sem az agytorna nem használt, nincs mese: ki kell kelni az ágyból! Este lefekvés előtt válassz ki a szobádban egy vonalkóddal ellátott terméket (fogkrém, müzlis doboz), és állítsd be az ébresztőt. Ha ezt megtetted, az olyan, mintha szerződést kötöttél volna az ördöggel: visszafordíthatatlan! Másnap reggel csak és kizárólag akkor tudod kikapcsolni az ébresztőt, ha ismét beolvasod az adott tárgy vonalkódját.<br>
    <img loading="lazy" class="alignnone size-medium wp-image-712" src="{{ asset('images/cikkek/alarm-355x768.jpg') }}" alt="" width="355" height="768"></p>
<p>Amennyiben azt veszed észre, hogy egyre több vonalkódos tárgy hever az ágyad körül, mert alvajárva magad köré hordod őket hajnalban, hogy reggel ne kelljen elmenni értük, akkor emeld a tétet! Olvasd be a másik emeleten lévő haverod valamelyik cuccán, vagy a nehezen mozdítható liftben lévő vonalkódot.</p>
<h2><x-a href="https://play.google.com/store/apps/details?id=com.malangstudio.alarmmon&amp;hl=hu" target="_blank" rel="noopener">4. AlarmMon</x-a></h2>
<p>Ha a napot egy adag cukisággal szeretnéd indítani, akkor válaszd ezt az appot! Nem is írok feleslegesen, nézd meg a videót, szerintem egy próbát mindenképpen megér.</p>
<p><iframe loading="lazy" src="https://www.youtube.com/embed/Ck1OwK3pBEw" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<h2><x-a href="https://play.google.com/store/apps/details?id=com.funanduseful.earlybirdalarm" target="_blank" rel="noopener">5. Early Bird Alarm Clock</x-a></h2>
<p>Én személy szerint azt az egyet utálom az átlagos ébresztőben, hogy mindig ugyanazt a hangot adja ki. Ha napközben véletlenül meghallom valahol, a hideg ráz ki! Valószínűleg éppen ezért találták ki az ehhez hasonló ébresztőket, ahol véletlenszerű dallamokkal indulhat a reggeled. Kikapcsolni vonalkód beolvasással, beszéddel, vagy előre megadott szöveg begépelésével tudod.</p>
<h2><x-a href="https://play.google.com/store/apps/details?id=com.moosa.alarmclock&amp;hl=hu" target="_blank" rel="noopener">6. Walk Me Up</x-a></h2>
<p>Még egy olyan ébresztő, ahol sétálgatni kell, csak itt nincs megadva, hogy hova, csak a lépésszámot kell beállítanod. Aki azt gondolná, hogy egyszerű rázogatással át tudja verni a telefont, az próbálkozhat vele, de ha az app csaláson kap, nullázza a lépések számát. Van benne Evil mód, ami kiveszi a szundi gombot, így esélyed sincs mászkálás nélkül kikapcsolni.</p>
<p><img loading="lazy" class="alignnone size-medium wp-image-715" src="{{ asset('images/cikkek/com.moosa_.alarmclock.png') }}" alt="" width="358" height="310"></p>
<p><x-a href="https://play.google.com/store/apps/details?id=com.spinmealarmclock" target="_blank" rel="noopener">7. SpinMe Alarm Clock</x-a></p>
<p>Ha fel akarod pörgetni a reggeled, akkor már kattinthatsz is ennek az appnak a linkjére! A kikapcsoláshoz fel kell állnod, majd pörögnöd-forognod. Gondolom felesleges említenem, hogy elég nehéz ezt ágyban megtenni, ha mégis sikerül, akkor is garantáltan felkelsz. A hangfájljaid közül választhatsz ébresztő zenét, én valami pörgős Szecsei mixet ajánlok!</p>
<p><img loading="lazy" class="alignnone size-medium wp-image-718" src="{{ asset('images/cikkek/SpinMe-AlarmClock.jpg') }}" alt="" width="700" height="400"></p>
<p><x-a href="https://play.google.com/store/apps/details?id=droom.sleepIfUCan" target="_blank" rel="noopener">+1. Alarmy</x-a></p>
<p>A végére hagytam azt az alkalmazást, ami a felhasználók saját bevallása szerint az egyik leggyűlöltebb, és legidegesítőbb ébresztő, mégis 4,7-es értékelése van 700.000 letöltés mellett. A kikapcsoláshoz fényképet kell készíteni egy előre megadott helyen, matek feladatot megoldani, vagy rázogatni a telefont.</p>
<p><img loading="lazy" class="alignnone size-medium wp-image-717" src="{{ asset('images/cikkek/81lVy8plfvL-432x768.png') }}" alt="" width="432" height="768"></p>
<p>Íme néhány értékelés, magukért beszélnek:</p>
<p><em>“Hihetetlenül hatásos, de tényleg. 8 éves korom óta gáz az ébredésem, de ezzel az appal kicseleztem ezt a nehézséget. Igazi pokol volt a felkelés-alvás dolog, de ennek vége. Köszönöm! Őszintén köszönöm!”</em></p>
<p><em>“Egyszerűen imádom! Rengeteget segít reggel a felkeléshez, és szó szerint teljesen személyre lehet szabni! Az ébresztő hangjától elkezdve az alkalmazás színétől és az ébresztési módjától bármit be lehet állítani! Mindenkinek tudom ajánlani!”</em></p>
<h2>Ahogy én csinálom</h2>
<p>Ahogy azt a <x-a href="{{ route('jobb-jegyek') }}">Jobb jegyek 10 lépésben könyvben</x-a> is írtam, a robot mód sok helyzetben lehet a segítségedre, így az ébredésnél is. Nekem már van egy olyan reggeli rutinom, aminek az első felében még bőven alszok, de a végére azért már magamhoz térek.</p>
<p>Abban a pillanatban ahogy megszólal a telefon, ösztönösen kelek ki az ágyból, megyek a fürdőbe egy fröccsenés vízért az arcomra, majd nekiállok lezavarni a 2 perces fogmosást az elektromos fogkefével. Idővel már telefonos ébresztésre sincs szükség (biztonság kedvéért mindig be van állítva), magától “kipattan” a szemem.</p>
<p>Az biztos, hogy az első 1-1.5 percben a világomat nem tudom, de már olyan szinten rutinná vált ez az egész, hogy a legkisebb erőfeszítés nélkül meg tudom tenni az ágy-fürdőszoba távolságot alvajárva.</p>
<p>Ha sikerült felkelned, és órára is be tudtál menni, akkor mutatok <x-a href="{{ route('articles.public_show', '10-lehetoseg-hogy-bekapcsolodj-az-egyetemi-eletbe') }}">10 lehetőséget, hogy bekapcsolódhass az egyetemi életbe.</x-a></p>
