<p>Nos, ha már veled is előfordult ilyesmi, akkor ajánlom figyelmedbe az <strong>Eisenhower mátrix</strong>ot, ami nekem nagyon sokat segített ezen a téren. A lényege, hogy a dolgokat sürgősségük és fontosságuk szerint 4 csoportba kell osztani, ezt láthatod a lenti képen:</p>
<p><a href="{{ asset('files/eisenhower-matrix.pdf') }}"><img loading="lazy" class="alignnone size-medium wp-image-805" src="{{ asset('images/cikkek/eisenhower-matrix-768x561.png') }}" alt="Eisenhower mátrix" width="768" height="561"></a></p>
<ol>
    <li>Hónap eleje van, a vállalkozásom adóit befizetni <strong>sürgős</strong>, mert 12-dike a határidő, <strong>és fontos</strong> is, mert ha nem fizetem be, akkor megbüntetnek. Akkor most abba is hagyom a gépelést, és megcsinálom… Kész 😀</li>
    <li>Cikket írni a Panda Egyetem oldalára<strong> fontos, azonban nem sürgős</strong>. Ennek oka, hogy elsősorban saját tapasztalataimat osztom meg veled. 2 havonta felugrik nekem egy emlékeztető: “Na, használtál valami új tanulási módszert amiről még eddig nem írtál?”, ha a válasz igen, akkor már ülök is a gép elé pötyögni. Ez a cikk is így született.</li>
    <li>11 óra van, a gyomrom már nagyon csikar, így elég <strong>sürgős</strong> lenne megfőzni azt az ebédet… Viszont annyira <strong>nem fontos</strong>, ha nem tudom rávenni a barátnőmet, hogy főzze meg helyettem, akkor eszek ebédre száraz kenyeret meg vizet. (Legalábbis ezt szoktam mondogatni drámai hangsúllyal, néha megesik rajtam a szíve és főz helyettem 😉 )</li>
    <li>Japánul megtanulni <strong>se nem fontos, se nem sürgős</strong>, csak egyszer kitaláltam, hogy nekem bizony meg kéne tanulnom, ha már egy csomó animét nézek. Tetszett a nyelvnek a hangzása, érdekes az írásuk, vagány ötletnek tűnt. De nagyon, NAGYON nehéz feladat, így nem csoda, hogy folyton halogattam. Tipikusan olyan dolog, ami csak foglalja a helyet azon az A4-es papíron, úgyhogy egy huszáros mozdulattal ki kell húzni róla.</li>
</ol>
<p>Vagy mégsem…?! Mivel engem nagyon érdekel maga a tanulás módszere, és kicsit mazochista is vagyok, kínkeserves módon rávettem magam, hogy ha törik, ha szakad valahogy megpróbálom ezt a negyedik rublikát is megoldani. Úgy tűnik jó úton haladok, úgyhogy a következő cikkem arról fog szólni, hogy a nem sürgős / nem fontos japán tanulást hogyan sikerült rendszeresítenem, és ennek segítségével hogyan tudod te is hatékonyabban elvégezni azokat a feladatokat, amik legalább sürgősek, vagy fontosak.</p>
<p>Visszakanyarodva az Eisenhower mátrixhoz, a kép alapján szerintem elég egyértelmű, hogy mit kell tenned, azért pontokba szedve leírom, biztos ami biztos:</p>
<ul>
    <li>Ami sürgős és fontos, annak állj neki most!</li>
    <li>Ami ráér, de fontos, hogy kész legyen, annak adj egy határidőt!</li>
    <li>Ami sürgős, de nem fontos, azt szervezd ki valaki másnak.</li>
    <li>Ami se nem sürgős, se nem fontos, azzal ne foglalkozz, csak az idődet pazarlod vele.</li>
</ul>
<p>Vegyük ezeket sorba, mindegyikhez van pár jótanácsom.</p>
<h3>Sürgős és fontos</h3>
<p>Általában azok a dolgok kerülnek ide, amiknek ma vagy holnap van a határideje, és az elvégzésükkel közelebb kerülsz egy kitűzött célodhoz, vagy legalább megőrzöd az eddig kiharcolt pozíciódat <em>(befizetem az adót, hogy megmaradhasson a vállalkozásom és ne büntessenek meg)</em>. Ami ebbe a kategóriába kerül, annak az elvégzésében általában valami motiválni fog: vagy komoly büntetést kapsz ha nem csinálod meg, vagy pedig nagy jutalom ütheti a markod, ha időben végzel vele. Amennyiben mégsincs ilyen, találj ki saját magadnak valami jutalmat vagy “büntetést” <em>(azért ne legyél túl szigorú).</em></p>
<h3>Ráér, de fontos</h3>
<p>Ha lehet, soha ne hagyj semmit az utolsó pillanatra. Olyan határidőt tűzz ki magadnak, ami még a tényleges határidő előtt van, de kezeld úgy, mintha ez lenne a végső időpont. Ha december 10 egy dolgozat beadásának a határideje, akkor a te határidőd legyen mondjuk december 6. Nyilván kell hozzá egy kis határozottság és elszántság, hogy ténylegesen is tartani tudd magad a december 6-hoz, de ha már csak félig megcsinálod a beadandót, akkor is előrébb vagy, mintha 9-dikén este ülnél le először foglalkozni vele.</p>
<h3>Sürgős de nem fontos</h3>
<p>A koliszobád kitakarítása, ha aznap szobaellenőrzés lesz, egy haverod telefonhívásának felvétele, vagy mondjuk élőben megnézni hajnalban egy NFL meccset. A szoba kitakarítását rá tudod sózni másra, a másik kettőnél viszont elég, ha találsz egy módot az elhalasztásra, és megpróbálod besúvasztani két “<em>sürgősésfontos</em>” feladatod közé.<br>
    Felveszed a telefont, és ha nem fontos, akkor majd visszahívod máskor a barátod. Átalszod az éjszakát, és megnézed a meccset felvételről.&nbsp;Az ökölszabáj az, hogy ha valamit sürgősnek érzel (<em>rád írnak és válaszolni “kell”, kedvenc csapatod játszik élőben</em>), akkor pillants rá az aktuális Eisenhower táblázatodra, és döntsd el, hogy van-e olyan fontos, mint az első rublikában lévő dolgok. Ha nem, akkor tudod-e használni bármelyiket két “<em>sürgősésfontos</em>” feladatod között mondjuk kikapcsolódásként.</p>
<h3>Nem sürgős, nem fontos</h3>
<p>Akkor minek van felírva? Valószínűleg azért, mert ez egyfajta bakancslista. Szeretnék megtanulni japánul, szeretnék elutazni a Kanári szigetekre… majd egyszer. Vagy kicsiben gondolkodva: Át kéne alakítani a lakást, meg kéne látogatni a régi osztálytársakat… majd egyszer. Ezekre egyáltalán nem szoktam feladatként tekinteni. Ha az összes többi lista üres, akkor ránézek, hogy miből lehet szemezgetni, nehogy véletlenül halálra unjam magam.</p>
<h3>Hol vezetheted ezeket a dolgokat?</h3>
<p>Egy sima A4-es lap kezdetben megteszi, vagy a fenti képet a példáim nélkül <a href="{{ asset('files/eisenhower-matrix.pdf') }}">letöltheted innen is</a>.<br>
    Sokkal célszerűbb azonban valami dinamikusabb dolgot használni, nekem például a <a href="https://play.google.com/store/apps/details?id=com.tarento.tasks" target="_blank" rel="noopener">Tasks nevű androidos alkalmazás</a> nagyon bejött. Még az egyes területeken belül is jelezheted magadnak színekkel, hogy valami a fontos dolgok között mennyire fontos, vagy a sürgősek közül melyiket kell azonnal megcsinálni, és melyik ér rá estig.</p>
<p><img loading="lazy" class="alignnone size-medium wp-image-807" src="{{ asset('images/cikkek/tasks.jpg') }}" alt="Tasks eisenhower android alkalmazás" width="424" height="576"></p>
<p>A <x-a href="{{ route('jobb-jegyek') }}">Jobb jegyek 10 lépésben: Hackeld meg az agyad</x-a> könyvemben 5 oldalon keresztül boncolgatom a témát egy teljesen más szemszögből.</p>
<x-a href="{{ route('jobb-jegyek') }}"><img loading="lazy" class="alignnone size-medium wp-image-162" src="{{ asset('images/cikkek/jobb-jegyek-10-lepesben-fb-preview-image-768x403.jpg') }}" alt="" width="768" height="403"></x-a></p>
