<p>Van egy mondás, mely szerint <strong>egy új szokás létrehozásához, mindössze 21 napra van szükség</strong>. Ha még nem hallottad, akkor gyorsan felejtsd is el, mert ez úgy nem igaz, ahogy van. Mielőtt bemutatnám a Habitica alapjait, nézzük meg mi az alapvető probléma.</p>
<h3>Jó szokások</h3>
<p>A szokások létrehozása egyén, és folyamat függő. Minél bonyolultabb dolgot szeretnél szokásoddá formálni, annál nehezebb lesz elérni, hogy rendszeresen végrehajtsd azt. Például napi 30 db húzódzkodás megvan 1 perc alatt, míg heti 1 cikk megírása 4-5 órát vesz igénybe (kutatás, kép gyűjtés, szerkesztés, lektorálás).</p>
<p>Előbbinél elég volt eleinte azt a trükköt bevetni, hogy a nappali ajtajába feltettem egy rudat, és minden nap amikor elhaladtam alatta, megcsináltam 1 húzódzkodást. A karomat az az 1-1 húzódzkodás nemigazán terhelte meg, azonban szépen lassan hozzászokott a mozgáshoz, és egy idő után már magamtól mentem csinálni a gyakorlatot.</p>
<p>Utóbbihoz jóval erősebb akarat kell, mert rengeteg szabadidőmet elveszi, nehéz motiváló tényezőt találni azon túl, hogy tudom: meg kell csinálnom.</p>
<h3>Rossz szokások</h3>
<p>A már meglévő rossz szokásokra éppen a fentiek az ellenkezője igaz. Apró rossz szokásokról majdhogynem nehezebb leszokni, mint az összetettekről.</p>
<p>Rágod a körmöd, vagy túrod az orrod? Az esetek többségében észre sem veszed, hogy éppen egy rossz szokásodnak vagy az áldozata. Leszokni róluk nehéz, mivel általában bekövetkezésük után eszmélsz rá, hogy megint rosszat tettél.</p>
<p>Ezzel ellentétben azt már nehéz nem észrevenni, ha lementél az irodaház elé elszívni egy szál cigit. Ha az épületben tilos a dohányzás, egy lépés lehet az önmegtartóztatásra, ha szünetben nem lépsz ki az épületből.</p>
<h3>Megoldás</h3>
<p>Akár apró, <strong>rossz szokásokról</strong> szeretnél <strong>leszokni</strong>, akár <strong>új szokásokat</strong> szeretnél <strong>létrehozni</strong>, mindenképpen <strong>motivációt kell</strong> találnod <strong>hozzá</strong>. Elsősorban <strong>ebben lesz segítségedre a Habitica</strong>.</p>
<p>Többek között folyamatok játékosításával is foglalkozom, ebbe pedig beletartozik a szokások létrehozása / megszüntetése.</p>
<p><strong>Miért fontos a játékosítás?</strong> Gondolj csak bele, hogy játék közben ugyanolyan dolgokat csinálsz újra és újra (Candy Crush, FarmVille, Pokemon Go), és mégsem hagyod abba. Ha rájövünk, hogy hogyan érik el a játékok azt, hogy ész nélkül csinálj ismétlődő folyamatokat anélkül, hogy fizetnének neked érte, akkor azt tök jó lenne alkalmazni más területen is.</p>
<p>A <a href="http://habitrpg.com/" target="_blank" rel="noopener">Habitica</a> éppen ezt oldotta meg a szokások területén: magasan tartja a motivációs szinted.</p>
<p>A Habitica egy weben, vagy telefonon futó játék, melyben csinálhatsz magadnak egy karaktert, akinek aranyat szerezhetsz, cuccokat vásárolhatsz, és akit fejleszthetsz. Önmagában már ez is képes lenne többeket motiválni, azonban van itt még más is: csatlakozhatsz csapatokhoz, és ez hozza meg igazán a varázsát!</p>
<p>A csapattal küldetéseket hajthatsz végre, de ha a napi szokásaidat nem teljesíted, az egész csapat sebződik miattad. Ahhoz, hogy ne haragítsd magadra őket, és egy jó csapat tagja maradhass, rendszeresen végre kell hajtanod a napi feladataidat. Illetve nem csak azt…</p>
<p>A helyzet az, hogy ez a platform nem csak új szokások létrehozására alkalmas, hanem kitűzött célok elérésére és rossz szokások elhagyására is. Ha belépsz, három kategóriába tudsz felvinni feladatokat:</p>
<figure id="attachment_738" aria-describedby="caption-attachment-738" class="wp-caption alignnone"><a href="{{ asset('images/cikkek/Capture-768x337.png') }}" class="fancybox image"><img loading="lazy" class="wp-image-738" src="{{ asset('images/cikkek/Capture-768x337.png') }}" alt="Habitica" width="768" height="337"></a><figcaption id="caption-attachment-738" class="wp-caption-text">Kattints a képre a részletekhez</figcaption></figure>
<h3>Szokások</h3>
<p>A szokások az első oszlopban csücsülnek, egy plusz és mínusz jellel az oldalukon. Én például Panda Egyetemes cikkek rendszeres írására szeretném rászoktatni magam, ezért a képen látható módon fel is vittem egy szokást a táblázatba. A mínusz oldala inaktív, mert nem jelent különösebb problémát ha nem írok cikket… ha viszont igen, akkor azt akarom, hogy a rendszer jutalmazzon érte!</p>
<p>Ennek az ellenkezője a csoki evés, amiről mindenképpen le szeretnék szokni. Itt nincs plusz oldal, mert nem szeretném magam minden egyes pillanatban jutalmazni amikor nem eszek csokit, helyette büntetni akarom magam amikor mégis.</p>
<p>A kettő közt helyezkedik el félúton a 10km-es futás, amit jutalmazni és büntetni is lehet. A cél, hogy hetente fussak 10km-t, így siker esetén jutalmazhatom magam, míg ha lusta disznó vagyok, akkor bizony elszenvedem a büntetést.</p>
<h3>Napi feladatok</h3>
<p>Ide tartoznak azok a dolgok, amiket rendszeresen meg kell csinálnod, de nem szeretnél belőlük pavlovi reflexet fejleszteni (csokit látok, és elmegy az étvágyam OK; koszos ruhát látok, és egyből ki akarom mosni NEM OK).</p>
<p>Én napi feladatnak tettem be a korán kelést és a reggelizést, mert hétvégente az egyik, munkanapokon a másik szokott elmaradni, pedig mindkettő fontos, ahogy az időben való ágyba bújás is. Lehetőség van olyan feladatok felvitelére is, melyek csak a hét bizonyos napján érvényesek, ilyen pl. a mosás, takarítás, amit hetente 1-2 alkalommal csinálok. Ha valamelyik éppen nem esedékes, akkor az ki van szürkítve, ahogy a képen is látszik.</p>
<p>Ha valamit nem teszel meg az adott napon, a rendszer automatikusan büntet érte. Ha megtetted, akkor pipáld ki, és jutalmat kapsz.</p>
<h3>Tennivalók</h3>
<p>Ide hosszútávú projekteket rögzítek, mint például egy kurzus elkészítése, egy könyv kiolvasása, vagy egy vizsga letétele. A rendszer nem ostoroz minden nap, hogy “Még mindig nem végezted el?!”, pusztán egyre pirosabb színnel jelöli őket, ahogy közeledik a határidő.</p>
<h3>Jutalom</h3>
<p>Miért csináljuk ezt az egészet? Egyrészt azért, mert rá szeretnénk venni magunkat olyan dolgok elvégzésére (vagy elhagyására), amik eddig valahogy nem mentek. Másrészt a játék megpróbál kétféle jutalom rendszerrel is ösztönözni.</p>
<p><img loading="lazy" class="alignnone size-medium wp-image-743" src="{{ asset('images/cikkek/habitica-jutalom.png') }}" alt="" width="472" height="624"></p>
<p>Az első a játékon belüli jutalom: pénz, varázstárgyak, fegyverek, harci hörcsög, és egy csomó más cucc, ami a játék sztorijában előre visz.</p>
<p>A második egy általad felállított jutalom halmaz: 1 óra játék, 15 perc szünet, vacsora egy étteremben… Olyan dolgok, amivel te leped meg saját magad, ha kiérdemelted őket.</p>
<h3>Ér valamit a Habitica?</h3>
<p>Nem egyszer csak azért kimentem sétálni egy órát az esőbe, hogy fejlődjön a hősöm <em>(a futásra való rászokást sétálással kezdtem)</em>. Nyilván a rendszer megköveteli a lelkiismeretes játékot, hisz akkor is bepipálhatod, hogy megvolt a séta, ha közben bent punnyadtál az ágyadban. Viszont ha nem vagy őszinte önmagaddal, akkor ne várd el, hogy jobb irányba mozdul majd az életed.</p>
<p>Az egész onnantól válik izgalmassá, hogy elkezdesz csapatokhoz csatlakozni, de nem akarom elrontani a felfedezés örömét. Ha van pénzed, fizethetsz játékbeli extra funkciókért, de én teljesen ingyenesen játszom, és nekem nagyon bejött úgy is!</p>
<p><x-a href="https://habitica.com/#/options/groups/guilds/4592e109-d7b9-4f84-a1dc-676b18743f71" target="_blank" rel="noopener">Csatlakozz a Panda Egyetem Habitica bandájához</x-a>, és segíts nekünk legyőzni a szörnyeket, és megszerezni a jobbnál jobb cuccokat.</p>
