<p>Elöljáróban annyit, hogy beköltözéskor kétféle kollégistával fogsz találkozni: az egyik kisbusszal érkezik és az egész rokonság segít neki a beköltözésben, a másikat elkíséri valamelyik szülője, két utazó táska van nála, és a 15 perces kipakolás után már bele is veti magát a kollégiumi életbe.</p>
<p>Ha az utóbbi kategóriába szeretnél tartozni, akkor ez a cikk neked szól!</p>
<h2>A kevesebb néha több</h2>
<figure id="attachment_40" aria-describedby="caption-attachment-40" class="wp-caption alignnone"><img loading="lazy" class="size-full wp-image-40" src="{{ asset('images/cikkek/Moving-into-Your-College-Dorm-or-Apartment-Tips.jpg') }}" alt="Kollégiumi beköltözés" width="900" height="599"><figcaption id="caption-attachment-40" class="wp-caption-text">Mindegy mennyi cuccot hozol, kiköltözésnél úgyis kétszer annyit kell majd hazavinned</figcaption></figure>
<p>Mi Pandák kőkemény kollégisták vagyunk, némelyikőnk mögött már több mint 10 év kollégiumi tapasztalat áll, íme néhány gondolat a témával kapcsolatban:</p>
<ol>
    <li><strong>A kollégiumi szoba kicsi</strong>. 2-3 ember lakik egy szobában, és bár nem kell nyomorogni, ha mindenki elhozza otthonról az összes cókmókját, 24 órából 1 biztosan azzal fog eltelni, hogy egyik helyről a másikra pakolgatjátok azokat.</li>
    <li><strong>Nem fogsz sok időt a szobádban tölteni. </strong>Leginkább az egyetemre jársz órákra, a könyvtárban kutatsz, a közösség helységben tanulsz, vagy a barátokkal ütöd el a felesleges időt. A szobába aludni, kockulni jársz majd csak vissza. (<em>Van kivétel, néha 1-1 szoba igazi főhadiszállás, ahol folyamatosan lógnak az emberek. Nézd meg <x-a href="https://hu.pinterest.com/pandaegyetem/koll%C3%A9gium-szoba/" target="_blank">Kollégium szoba Pinterest falunkat!</x-a></em>)</li>
    <li><strong>A dolgok 70%-át szinte alig fogod használni</strong>. A sok öntevékeny körnek hála, van audió és videó stúdió, kondi terem, társasjátékok, kondi terem és még egy csomó más, amit használhatsz.</li>
    <li><strong>Sokminden feleslegessé válik, mert szobatársad is viszi. </strong>Ilyenek például az edények főzéshez, robotgép, kisrádió, de rengetegen hoznak ágynemü huzatot, pedig az alanyi jogon jár minden kollégistának.</li>
</ol>
<h2>Dolgok amiket ne felejts otthon, ha kollégista lettél</h2>
<h4>Papucs, flip-flop</h4>
<figure id="attachment_23" aria-describedby="caption-attachment-23" class="wp-caption aligncenter"><img loading="lazy" class="wp-image-23 size-full" src="{{ asset('images/cikkek/sor-flip-flop.jpg') }}" alt="Sör flip-flop" width="450" height="450"><figcaption id="caption-attachment-23" class="wp-caption-text">Legyen vagány, könnyebb vele ismerkedni!</figcaption></figure>
<p>Nem mindenkinek jut eszébe, hogy egy zuhanyzót többen, néha 30-40 emberrel együtt használtok. Nem kell kifejezetten igénytelennek lenni ahhoz, hogy az ember elkapjon egy lábgombát, és máris útjára indul a fertőzés, ha nem papucsban mentek fürdeni.</p>
<p>Továbbá a koliban szinte folyamatosan 20 fok felett van a hőmérséklet, ha egész nap cipőban vagy, lehet bármilyen márkás, garantáltan belerohad a lábad. Kolikon belül szoktak lenni büfék, illetve rajtunk kívül is rengeteg étterem szállít házhoz, még az épületet sem kell elhagynotok.</p>
<h4>Tisztálkodó szerek, WC papír</h4>
<figure id="attachment_24" aria-describedby="caption-attachment-24" class="wp-caption aligncenter"><img loading="lazy" class="size-full wp-image-24" src="{{ asset('images/cikkek/penz-kereses-egyetemen-lany-autot-mos.jpg') }}" alt="Lány autót mos" width="600" height="400"><figcaption id="caption-attachment-24" class="wp-caption-text">Így is lehet, a lényeg, hogy a végén tiszta legyél…</figcaption></figure>
<p>Első alkalommal mindenképpen hozz magaddal mindkettőt. Elég sok bolt van a koleszok környékén, így később be tudsz itt is vásárolni, de ki tudja meddig tart feltérképezni a környéket. A Központi koliban például biztosítják a <strong>wc papír</strong>t, de itt sem árt, ha van egy tartalék tekercs, mert néha kifogy.</p>
<p>Talán ide tartozik még a tisztító szer is, mint a <strong>mosópor</strong>. Legjobb tudomásunk szerint mindegyik koliban <strong>van lehetőség mosógépet használni</strong>, így egy heti ruha mennyiséggel akár életed végéig is kihúzhatnád itt.</p>
<h4>Laptop</h4>
<figure id="attachment_25" aria-describedby="caption-attachment-25" class="wp-caption aligncenter"><img loading="lazy" class="wp-image-25 size-full" src="{{ asset('images/cikkek/egyetem-macbook-laptop-osztaly.jpg') }}" alt="Egyetem macbook laptop előadás" width="500" height="246"><figcaption id="caption-attachment-25" class="wp-caption-text">Nem kell a legújabb macbook, de valamilyen laptop legyen nálad</figcaption></figure>
<p>Nem tudjuk, hogy manapság mennyire kirívó eset az, ha egy 18 évesnek nincs laptopja, egy valamit viszont tudunk: <strong>egyetemen laptop nélkül esélyed sincs.</strong></p>
<p>Szinte minden karon vannak olyan tárgyak, amikhez neten kell leadni a házit, vagy onnan tudod letölteni a tananyagot. Heti szinten nézned kell a Neptun rendszert, ahol tárgyat vehetsz fel, vizsgára jelentkezhetsz, kolidíjat fizethetsz be. Itt a laptop már nem luxus cikk, hanem alapvető felszerelés.</p>
<p>Nálunk is kedvezményeket kapnak azok, akik neten keresztül adják le a rendeléseket, azokkal szemben, akik telefonon rendelnek. Például ha fliratkozol hírlevelünkre, küldünk neked egy “Jobb jegyek, kevesebb tanulás 10 lépésben” könyvet.</p>
<h4>Füzet, toll, számológép</h4>
<figure id="attachment_26" aria-describedby="caption-attachment-26" style="width: 799px" class="wp-caption alignnone"><img loading="lazy" class="size-full wp-image-26" src="{{ asset('images/cikkek/tanulas-felszereles.jpg') }}" alt="Tanulás felszerelés" width="799" height="215"><figcaption id="caption-attachment-26" class="wp-caption-text">Jegyzetelj, vizsgázáskor jól jön átnézni</figcaption></figure>
<p>Az anyag nagyrésze fent van neten, azonban <strong>órán mindig érdemes jegyzetelni</strong>. <em>(A jó jegyzetekért van aki még fizetni is hajlandó.) </em></p>
<p>Tollból nem érdemes a legolcsóbbat megvenni, mert az első leejtésnél törik benne a hegy. Azonban 400 Ft-nál többet sem adnánk ki érte, mert az már lehúzás. Ceruzával nem javasoljuk a jegyzetelést, mert idővel megfakul, és nem tudhatod, hogy 3 vagy 7 év alatt végzed el az egyetemet…</p>
<p>Számológép a matek tárgyakhoz nélkülözhetetlen. Onnan tudod, hogy analízis vagy valószínűségszámítás vizsga van, hogy a FB tele lesz “Kinekvankölcsönbeszámológépe” postokkal.</p>
<h4>Ruha</h4>
<figure id="attachment_27" aria-describedby="caption-attachment-27" style="width: 800px" class="wp-caption alignnone"><img loading="lazy" class="size-full wp-image-27" src="{{ asset('images/cikkek/egyetem-polo.jpg') }}" alt="Egyetem polo" width="800" height="394"><figcaption id="caption-attachment-27" class="wp-caption-text">Az elején úgyis kapsz vagy 4 féle ajándék pólót kolis és egyetemi logóval</figcaption></figure>
<p>1 hétre elegendő ruhával vágj neki az útnak, mosásra van lehetőség. Ha még nem mostál, kitűnő ürügy a lányokkal való ismerkedésre. Tartsd észben, hogy általában egy kisebb akasztós szekrény áll majd rendelkezésedre, plusz egy fiókos a fehérneműknek, szóval lehetőleg csak az évszaknak megfelelő ruhákat pakold be.</p>
<h4>Gyógyszer</h4>
<p><img loading="lazy" class="alignnone size-medium wp-image-58" src="{{ asset('images/cikkek/gyogyszer-1-768x406.jpg') }}" alt="Gyógyszer" width="768" height="406"></p>
<p><strong>Rettentő fontos</strong>! A kollégiumok recepcióján nem fognak neked adni sem fájdalom sem lázcsillapítót, mivel belső szabályzat tiltja! Ez azért van, mert nem lehet tudni, kinek milyen gyógyszer allergiája van, és a recepciós nem vállalhat ilyesfajta kockázatot. Magadat is bebiztosítod azzal. ha nem másoktól kérsz, hanem a sajátodat használod, ugyanis az öreg rókáknál lehet, hogy van egy algoflex, viszont nagy az esély rá, hogy már rég lejárt. Mi is futottunk már bele ilyenbe.</p>
<h2>Ennyi?</h2>
<p>Első körben <strong>teljesen felesleges többet hozni.</strong> Először mérd fel a terepet, első héten úgyis csak buli van és ismerkedés. Meg tudjátok beszélni szobatársakkal, hogy ki mit hozzon, így a haza cuccolás is egyszerűbb lesz.</p>
<p>Több cikket is írtunk ebben a témában, egyik egy <x-a href="{{ route('articles.public_show', '60-dolog-ami-nelkul-ne-koltozz-koliba') }}">hosszú pipálgatós listát</x-a> tartalmaz azoknak, akik maximalisták és semmit nem szeretnének otthon felejteni, a másik pedig arra hívja fel a figyelmet, hogy <x-a href="{{ route('articles.public_show', 'kollegiumi-bekoltozes-mit-ne-felejts-otthon') }}">milyen dolgokat ne hozzunk semmiképpen egy kollégiumba</x-a>.<strong> Utóbbi megspórolhat egy felesleges hazapakolós utat.</strong></p>
